### ISSUE TITLE
Implementacija modela podataka u Android Studiju

### ISSUE THREAD

**Issue by anagustek** [AIR-FOI-HR/AIR1921#10]
Izraditi model podataka u aplikaciji i povezati aplikaciju s Firebase bazom podataka.

![ERA.png](https://images.zenhubusercontent.com/5dc951750f20bf0001e1aa97/5c1a072b-72a1-4c50-9c28-e5b52284ccda)

**Comment by bkavur** [comment]
Pregledan kod i odobren pull request.
