### ISSUE TITLE
Nadopuna tehničke dokumentacije

### ISSUE THREAD

**Issue by anagustek** [AIR-FOI-HR/AIR1921#97]
Nadopuna prve verzije tehničke dokumentacije s novokreiranim elementima.

**Comment by anagustek** [comment]
Dodan use case dijagram i opisana specifikacija korisničkih zahtjeva.

**Comment by anagustek** [comment]
Funkcionalnosti objašnjenje kroz dijagrame aktivnosti.

**Comment by bkavur** [comment]
Dodan opis modularnosti i dijagram klasa.
